config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "stats", to: "static_pages#stats"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, path: :members do
    resource :admin, only: %i(create destroy)
  end
  resources :songs
  resources :lives
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)

  namespace :api, format: "json" do
    namespace :v1 do
      resources :users, only: %i[index show], path: :members
      resources :lives, only: %i[index show]
      resources :songs, only: %i[index show]
      post "/login", to: "tokens#create"
      delete "/logout", to: "tokens#destroy"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  attr_reader :remember_token
  attr_accessor :activation_token, :reset_token

  before_save :email_downcase
  before_save :remove_spaces_from_furigana
  before_create :create_activation_digest

  has_many :playings, dependent: :restrict_with_exception
  has_many :songs, through: :playings
  has_many :tokens, dependent: :destroy

  validates :first_name, presence: true,
    length: {maximum: Settings.firstname_max_length}
  validates :last_name, presence: true,
    length: {maximum: Settings.lastname_max_length}
  validates :furigana, presence: true
  validates :nickname,
    length: {maximum: Settings.nickname_max_length}
  validates :email, presence: true,
    length: {maximum: Settings.email_max_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}, allow_nil: true
  validates :joined, presence: true,
    numericality: {
      only_integer: true,
      greater_than: Settings.year_joined,
      less_than_or_equal_to: Date.today.year
    }
  validates :password, presence: true,
    length: {minimum: Settings.password_min_length}, allow_nil: true
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/,
    allow_blank: true

  scope :natural_order, -> { order("joined DESC") }
  scope :distinct_joined, lambda {
    unscope(:order).select(:joined).distinct.order(joined: :desc).pluck(:joined)
  }

  has_secure_password

  def formal_name
    "#{last_name} #{first_name}"
  end

  def full_name logged_in = true
    return handle unless logged_in

    if nickname.blank?
      formal_name
    else
      "#{last_name} #{first_name} (#{nickname})"
    end
  end

  def kana
    furigana.gsub(/\s+/, "")
  end

  def handle
    nickname.blank? ? last_name : nickname
  end

  def elder?
    joined < 2011
  end

  def admin_or_elder?
    admin? || elder?
  end

  def played? song
    playings.map(&:song_id).include?(song.id)
  end

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"

    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def current_user? user
    user == self
  end

  def forget
    update_attributes remember_digest: nil
  end

  def activate
    update_attributes activated: true
    update_attributes activated_at: Time.zone.now
  end

  def send_activation_email
    email = {user_name: self.first_name, activation_token: self.activation_token,
      mail: self.email}
    UserMailer.account_activation(email).deliver_later
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes reset_digest: User.digest(reset_token)
    update_attributes reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    pass_reset = {reset_token: self.reset_token, mail: self.email}
    UserMailer.password_reset(pass_reset).deliver_later
  end

  def password_reset_expired?
    reset_sent_at < Settings.hours_max.hours.ago
  end

  def valid_token? token
    digests = tokens.pluck(:digest)
    digests.any? { |d| BCrypt::Password.new(d).is_password?(token) }
  end

  def destroy_token token
    token = tokens.find { |t| BCrypt::Password.new(t.digest).is_password?(token) }
    token.destroy if token
  end

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

  def email_downcase
    self.email = email.downcase unless email.nil?
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end

  def remove_spaces_from_furigana
    self.furigana = furigana.gsub(/\s+/, "")
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :check_public, only: :show

  def index
    if params[:active] != "true"
      @users = User.natural_order
    else
      today  = Date.today
      range  = (today - 1.year..today)
      @users = User.natural_order.includes(songs: :live).where("lives.date" => range)
    end
  end

  def show
    @playings = Playing.where(song_id: @user.songs.pluck("songs.id"))
  end

  private

  def check_public
    @user = User.includes(songs: :live).find(params[:id])
    request_http_token_authentication unless @user.public? || authenticated?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i[index show]
  before_action :check_public, only: :show
  before_action :find_user, only: %i[edit update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_or_elder_user, only: :destroy

  def index
    if params[:active] != "true"
      @users = User.natural_order
    else
      today = Date.today
      range = (today - 1.year..today)
      @users = User.natural_order.includes(songs: :live).where("lives.date" => range)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new create_user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @playings = Playing.where(song_id: @user.songs.pluck("songs.id"))
  end

  def edit; end

  def update
    if @user.update_attributes update_user_params
      flash[:success] = "Profile update successfully!"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Delete user successfully!"
    else
      flash[:danger] = "Something went wrong!"
    end
    redirect_to users_path
  end

  private

  def create_user_params
    params.require(:user).permit :first_name, :last_name,
      :furigana, :email, :joined, :password
  end

  def update_user_params
    params.require(:user).permit :first_name, :last_name,
      :furigana, :nickname, :email, :joined, :password,
      :password_confirmation, :url, :intro, :public
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = "Cannot find this user!"
    redirect_to root_path
  end

  def correct_user
    redirect_to root_path unless @user.current_user? current_user
  end

  def check_public
    @user = User.includes(songs: :live).find(params[:id])
    redirect_to root_path unless logged_in? || @user.public?
  end
end

app/views/users/_form.html.erb
<div class="form-group">
  <%= f.label :first_name, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :first_name, class: "form-control", placeholder: "Phúc", required: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :last_name, class: "form-control", placeholder: "Đặng Xuân", required: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :furigana, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :furigana, class: "form-control", placeholder: "furigana", required: true %>
  </div>
</div>
<% if full %>
  <div class="form-group">
    <%= f.label :nickname, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :nickname, class: "form-control",
        placeholder: "nickname", required: true %>
    </div>
  </div>
<% end %>
<div class="form-group">
  <%= f.label :email, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.email_field :email, class: "form-control",
      placeholder: "example@livelog.com", required: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :joined, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.select :joined, (1995..nendo).to_a.reverse,
      {}, {class: "form-control"} %>
  </div>
</div>
<% if full %>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :url, class: "form-control",
        placeholder: "https://livelog.com/" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :intro, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area :intro, class: "form-control", rows: "3",
        placeholder: "Lorem ipsum dolor sit amet" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9">
      <label class="radio-inline">
        <%= f.radio_button :public, "true" %> Public
      </label>
      <label class="radio-inline">
        <%= f.radio_button :public, "false" %> Private
      </label>
      <br><small class="help-block">
        「公開」にしても，名前とメールアドレスが公開されることはありません。
        <br>
        ただし，ニックネームが存在しない場合，姓は公開されます
      </small>
    </div>
  </div>
<% end %>
<div class="form-group">
  <%= f.label :password, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.password_field :password, class: "form-control", required: true %>
  </div>
</div>
<% if full %>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.password_field :password_confirmation, class: "form-control", required: true %>
    </div>
  </div>
<% end %>
<div class="form-group">
  <div class="col-sm-offset-3 col-sm-9">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
</div>

app/views/users/_panel.html.erb
<div class="col-xs-6 col-sm-3 col-md-2">
  <section class="panel panel-default">
    <header class="panel-heading">
      <h2 class="panel-title"><%= title %></h2>
    </header>
    <%= yield %>
  </section>
</div>

app/views/users/_user.html.erb
<li>
  <% if logged_in? || user.public? %>
    <%= link_to user do %>
      <%= user.full_name(logged_in?) %>
    <% end %>
    <% if logged_in? && user.admin? %>
      <span>*</span>
    <% end %>
  <% else %>
    <%= user.full_name(logged_in?) %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %>
<% provide :button_text, "Save" %>
<header class="page-header">
  <h2>Update your profile</h2>
</header>
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= render "form", f: f, full: true %>
<% end %>

app/views/users/index.html.erb
<% provide :title, "Members" %>
<header class="page-header">
  <h2>Members</h2>
</header>
<aside class="form-inline">
  <div class="checkbox">
    <label>
      <%= check_box_tag :active, true, false, checked: params[:active] == "true",
        onchange: "location.href='#{request.path}?active=' + $(this).is(':checked');" %>
      1年以内にライブに出演したメンバーのみ表示
    </label>
  </div>
</aside>
<% @users.distinct_joined.each_slice(4) do |four_y| %>
  <div class="row">
    <% four_y.each do |y| %>
      <div class="col-sm-3">
        <h2><%= y %></h2>
        <ol>
          <% @users.select { |u| u.joined == y }.each do |user| %>
            <% cache_unless logged_in?, user do %>
              <%= render user %>
            <% end %>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
<% end %>
<% if logged_in? %>
  <p>* 印が付いているメンバーは管理者です。</p>
<% end %>

app/views/users/new.html.erb
<% provide :title, "Add member" %>
<% provide :button_text, "Sign up" %>
<header class="page-header">
  <h2>Add Member</h2>
</header>
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= render "form", f: f, full: false %>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.full_name(logged_in?) %>
<% total = @user.songs.count %>
<header class="page-header">
  <h2><%= @user.full_name(logged_in?) %>
    <% if logged_in? %>
      <small>
        <%= @user.joined %>
        <% if !@user.public? %>
          <%= glyphicon(:lock) %>
        <% end %>
      </small>
    <% end %>
  </h2>
</header>
<div class="row">
  <%= render "panel", title: "出演数・楽器" do %>
    <div class="panel-body text-center lead">
      <mark><%= total %></mark> 曲
    </div>
    <ul class="list-group lead">
      <% Playing.resolve_insts(@user.playings.count_insts).each do |inst, count| %>
        <% unless inst.blank? %>
          <li class="list-group-item">
            <span class="badge badge-primary"><%= count %></span>
            <%= inst %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
  <% unless total == 0 %>
    <%= render "panel", title: "アーティスト" do %>
      <ul class="list-group">
        <% @user.songs.group(:artist).count.sort { |(k1, v1), (k2, v2)| v2 <=> v1 }.take(20).each do |artist, count| %>
          <% if count >= 2 && (count.to_f / total) >= 0.04 && !artist.blank? %>
            <li class="list-group-item">
              <span class="badge badge-primary"><%= count %></span>
              <%= artist %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
    <%= render "panel", title: "共演者" do %>
      <div class="panel-body">
        <mark><%= @playings.group(:user).count.size - 1 %></mark>人
        <ul class="list-group">
          <% @playings.group(:user).count.sort{ |(k1, v1), (k2, v2)| v2 <=> v1 }.take(20).each do |user, count| %>
            <% if user != @user && count >= 2 && ((count.to_f / total) >= 0.2 || count >= 10) %>
              <li class="list-group-item">
                <span class="badge badge-primary"><%= count %></span>
                <%= logged_in? || user.public? ? link_to(user.full_name(logged_in?), user) : user.handle %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= render "panel", title: "構成人数" do %>
      <ul class="list-group">
        <% sum = 0 %>
        <% Playing.count_formation(@playings.count_members_per_song).each do |formation, count| %>
          <li class="list-group-item">
            <span class="badge badge-primary"><%= count %></span>
            <%= "#{formation}人" %>
          </li>
          <% sum += formation * count %>
        <% end %>
      </ul>
      <div class="panel-body">
        平均<%= (sum.to_f / total).round(2) %>人
      </div>
    <% end %>
  <% end %>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <section class="panel panel-default">
      <header class="panel-heading">
        <h2 class="panel-title">自己紹介</h2>
      </header>
      <div class="panel-body">
        <dl>
          <% if logged_in? && current_user.admin? && !@user.email.blank? %>
            <dt>Email</dt>
            <dd><%= mail_to @user.email %></dd>
          <% end %>
          <% unless @user.url.blank? %>
            <dt>URL</dt>
            <dd><%= link_to @user.url, @user.url, target: "_blank" %></dd>
          <% end %>
        </dl>
        <%= simple_format(@user.intro) %>
      </div>
    </section>
  </div>
</div>

<%= render "songs/songs_table",
  songs: @user.songs.order_by_live.includes(playings: :user) %>

<% if logged_in? && current_user.admin? %>
  <div class="float-right list-inline">
    <% if current_user.admin_or_elder? && !@user.songs.exists? %>
      <%= link_to glyphicon(:trash) + "Delete", @user, method: :delete, class: "btn btn-danger" %>
    <% elsif current_user.admin? && current_user != @user %>
      <% if @user.admin? %>
        <%= link_to "Remove role admin", user_admin_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Set role admin", user_admin_path(@user), method: :post, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
<% end %>