config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "stats", to: "static_pages#stats"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, path: :members do
    resource :admin, only: %i(create destroy)
  end
  resources :songs
  resources :lives
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)

  namespace :api, format: "json" do
    namespace :v1 do
      resources :users, only: %i[index show], path: :members
      resources :lives, only: %i[index show]
      resources :songs, only: %i[index show]
      post "/login", to: "tokens#create"
      delete "/logout", to: "tokens#destroy"
    end
  end
end

app/models/song.rb
class Song < ApplicationRecord
  VALID_YOUTUBE_REGEX =
    %r(\A
      (?:
        (?<id>\S{11})\z
          |(?:https?://)?
        (?:www\.youtube\.com/watch\?(?:\S*&)*v=
          |youtu\.be/)
        (?<id>\S{11})
      )
    )x

  enum status: {
    secret: 0,
    closed: 1,
    open: 2
  }

  belongs_to :live, touch: true
  has_many :playings, dependent: :destroy, inverse_of: :song
  has_many :users, through: :playings
  accepts_nested_attributes_for :playings, allow_destroy: true

  validates :live_id, presence: true
  validates :name, presence: true
  validates :youtube_id, format: {with: VALID_YOUTUBE_REGEX},
    allow_blank: true
  before_save :extract_youtube_id

  scope :played_order, -> { order(:time, :order) }
  scope :order_by_live, lambda {
    includes(:live).order("lives.date DESC", :time, :order)
  }
  scope :visible, -> { where("lives.date < ?", Date.today + 1.week) }

  def self.search query, page
    q = "%#{query}%"
    where("songs.name ILIKE ? OR artist ILIKE ?", q, q)
      .order_by_live.paginate(page: page)
  end

  def extract_youtube_id
    return if youtube_id.blank?

    m = youtube_id.match(VALID_YOUTUBE_REGEX)
    self.youtube_id = m[:id]
  end

  def title
    artist.blank? ? name : "#{name} / #{artist}"
  end

  def youtube_url
    "https://www.youtube.com/watch?v=#{youtube_id}" unless youtube_id.blank?
  end

  def youtube_embed
    %(<iframe src="https://www.youtube.com/embed/#{youtube_id}?rel=0" frameborder="0" allowfullscreen></iframe>).html_safe
  end

  def time_str
    time.strftime("%R") unless time.blank?
  end

  def time_order
    "#{time_str} #{order}"
  end

  def previous logged_in = false
    return nil if order.blank?

    allowed_statuses = if logged_in
                         [Song.statuses[:open], Song.statuses[:closed]]
                       else
                         [Song.statuses[:open]]
                       end
    Song.where(live: live, status: allowed_statuses)
      .where("(songs.order < ? OR songs.time < ?) AND NOT (songs.youtube_id IS NULL OR songs.youtube_id = '')", order, time).last
  end

  def next logged_in = true
    return nil if order.blank?

    allowed_statuses = if logged_in
                         [Song.statuses[:open], Song.statuses[:closed]]
                       else
                         [Song.statuses[:open]]
                       end
    Song.where(live: live, status: allowed_statuses)
      .where("(songs.order > ? OR songs.time > ?) AND NOT (songs.youtube_id IS NULL OR songs.youtube_id = '')", order, time).first
  end
end

app/controllers/api/v1/songs_controller.rb
class Api::V1::SongsController < Api::V1::ApplicationController
  def index
    @songs = Song.search(params[:q], params[:page])
  end

  def show
    @song = Song.includes(playings: :user).find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_song, only: %i[show edit update destroy]
  before_action :logged_in_user, except: %i[index show]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_or_elder_user, only: %i[new create destroy]
  before_action :store_referer, only: :edit

  def index
    @songs = Song.visible.includes(playings: :user).search(params[:q], params[:page])
  end

  def new
    live = params[:live_id] ? Live.find(params[:live_id]) : Live.first
    @song = live.songs.build
    @song.playings.build
  end

  def create
    @song = Song.new song_params
    if @song.save
      flash[:success] = "曲を追加しました"
      redirect_to @song.live
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
      if @song.update song_params
        flash[:success] = "Update song successfully!"
        redirect_back_or @song
      else
        render :edit
      end
  end

  def destroy
    live = @song.live
    @song.destroy
    flash[:success] = "Delete song successfully!"
    redirect_back_or live
  end

  private

  def find_song
    @song = Song.includes(playings: :user).find_by id: params[:id]

    return if @song
    flash[:danger] = "Cannot find this song"
    redirect_to live_path
  end

  def song_params
    params.require(:song).permit :live_id, :time, :order,
      :name, :artist, :youtube_id, :status, :comment,
      playings_attributes: %i[id user_id inst _destroy]
  end

  def store_referer
    session[:forwarding_url] = request.referer || root_path
  end

  def correct_user
    redirect_to root_path unless current_user.played?(@song) || current_user.admin_or_elder?
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  # list order of instruments
  INST_ORDER = %w[Vo Vn Vla Vc Fl Cl Sax Tp Hr Tb Harp Gt Koto Pf Acc 鍵ハ Ba Cj Dr Bongo Perc].freeze

  def sort_by_inst playings
    playings.sort do |p1, p2|
      inst_order(p1.inst) <=> inst_order(p2.inst)
    end
  end

  def can_watch? song
    !song.youtube_id.blank? && (song.open? || song.closed? && logged_in? || logged_in? && current_user.played?(song))
  end

  def can_edit? song
    logged_in? && (current_user.admin_or_elder? || current_user.played?(song))
  end

  def button_to_add_member text, f
    fields = f.fields_for(:playings, @song.playings.build) do |builder|
      render "songs/playings_fields", f: builder
    end
    content_tag :button, text, id: "add-member", type: "button", class: "btn btn-link", data: { fields: fields.gsub("\n", "") }
  end

  private

  def inst_order inst
    priority = INST_ORDER.index { |i| inst.include?(i) }
    priority ? priority : INST_ORDER.size
  end
end

app/views/songs/_form.html.erb
<%= form_for(@song, html: {class: "form-horizontal"}) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :live_id, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.collection_select :live_id, Live.order_by_date, :id, :title, {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :youtube_id, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.text_field :youtube_id, value: @song.youtube_url, class: "form-control", placeholder: "https://www.youtube.com/watch?v=sSbqm7ZK_9s" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :order, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :order, class: "form-control", placeholder: "1" %>
    </div>
  </div>
  <% if @song.live.name.include?("NF") %>
    <div class="form-group">
      <%= f.label :time, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.time_field :time, class: "form-control", placeholder: "10:00" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control", placeholder: "Tears in Heaven" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :artist, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :artist, class: "form-control", placeholder: "Eric Clapton" %>
    </div>
  </div>
  <div id="playings-fields">
    <%= f.fields_for :playings do |builder| %>
      <%= render "playings_fields", f: builder %>
    <% end %>
  </div>
  <div class="form-group">
    <div class="col-sm-3 control-label">
      <%= button_to_add_member glyphicon("plus"), f %>
    </div>
  </div>
  <% if current_user.played?(@song) %>
    <div class="form-group">
      <%= f.label :status, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.select :status, {"Private": "secret", "Closed": "closed", "Public": "open"}, {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :comment, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.text_area :comment, class: "form-control", rows: 3 %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      <% if @song.persisted? && current_user.admin_or_elder? %>
        <%= link_to glyphicon(:trash) + "Delete", @song, method: :delete,
          data: {confirm: "Are you sure?"}, class: "btn btn-danger float-right",
          role: "button" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/songs/_link_to_edit.html.erb
<% if can_edit? song %>
  <%= link_to glyphicon(:edit), edit_song_path(song) %>
<% end %>
<% if logged_in? && current_user.played?(song) %>
  <% if song.open? %>
    <%= glyphicon(:globe) %>
  <% elsif song.secret? %>
    <%= glyphicon(:lock) %>
  <% end %>
<% end %>

app/views/songs/_panel.html.erb
<div class="col-sm-6 col-md-3">
  <section class="panel panel-default">
    <header class="panel-heading">
      <h2 class="panel-title"><%= title %></h2>
    </header>
    <%= yield %>
  </section>
</div>

app/views/songs/_playings_fields.html.erb
<%= f.hidden_field :_destroy, value: 0 %>
<div class="form-group" id="song_playings_attributes_<%= f.index %>_fields">
  <%= f.label :user, class: "col-sm-3 control-label" %>
  <div class="col-sm-2">
    <%= f.text_field :inst, class: "form-control", placeholder: "Gt&Vo" %>
  </div>
  <div class="col-sm-6">
    <%= f.collection_select :user_id, User.natural_order, :id, :full_name, {}, class: "select2 form-control" %>
  </div>
  <div class="col-sm-1">
    <%= content_tag :button,
      glyphicon(:minus), type: "button",
      class: "remove-member btn btn-link",
      data: {prefix: "song_playings_attributes_#{f.index}"} %>
  </div>
</div>

app/views/songs/_search_form.html.erb
<%= form_tag "/songs", method: "get", class: "form-inline" do %>
  <div class="form-group">
    <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "Song / Artist" %>
  </div>
  <%= button_tag glyphicon(:search) + "Search", class: "btn btn-primary" %>
<% end %>

app/views/songs/_song.html.erb
<tr>
  <td><%= link_to song.live.title, song.live %></td>
  <td><%= song.time_order %></td>
  <td><%= can_watch?(song) ? link_to(song.name, song) : song.name %></td>
  <td><%= song.artist %></td>
  <td>
    <ul class="list-inline">
      <%= render sort_by_inst(song.playings) %>
    </ul>
  </td>
  <td><%= render "songs/link_to_edit", song: song %></td>
</tr>

app/views/songs/_songs_table.html.erb
<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Live</th>
        <th>#</th>
        <th>Song</th>
        <th>Artist</th>
        <th>Members</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% songs.each do |song| %>
        <% cache_unless logged_in?, song do %>
          <%= render song %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/songs/edit.html.erb
<% provide :title, "Edit song" %>
<% provide :button_text, "Save" %>
<header class="page-header">
  <h2>Edit song</h2>
</header>
<%= render "form" %>

app/views/songs/index.html.erb
<% provide :title, "Song Search" %>
<header class="page-header">
  <h2>Song Search</h2>
</header>
<%= render "search_form" %>
<% if @songs.present? %>
  <p class="text-right">
    <%= page_entries_info %>
  </p>
  <%= render "songs/songs_table", songs: @songs %>
  <%= paginate @songs, theme: "twitter-bootstrap-4" %>
<% else %>
  <div class="alert alert-danger" role="alert">
    <strong><%= params[:q] %></strong>に一致する曲は見つかりませんでした。
  </div>
<% end %>

app/views/songs/new.html.erb
<% provide :title, "Add song" %>
<% provide :button_text, "Add" %>
<header class="page-header">
  <h2>Add song</h2>
</header>
<%= render "form" %>

app/views/songs/show.html.erb
<% provide :title, "#{@song.name} | #{@song.live.title}" %>
<article>
  <header class="page-header">
    <h2>
      <%= @song.title %>
      <small><%= render "link_to_edit", song: @song %></small><br>
    </h2>
  </header>
  <ol class="breadcrumb">
    <li><%= link_to "Live List", lives_path %></li>
    <li><%= link_to @song.live.title, @song.live %></li>
    <li class="active"><%= "#{@song.time_order} #{@song.name}" %></li>
  </ol>
  <div class="row">
    <% if can_watch?(@song) %>
      <div class="col-sm-12 col-md-9">
        <p class="embed-responsive embed-responsive-16by9">
          <%= @song.youtube_embed %>
        </p>
      </div>
    <% end %>
    <%= render "panel", title: "Members" do %>
      <ul class="list-group">
        <%= render sort_by_inst(@song.playings), klass: "list-group-item" %>
      </ul>
    <% end %>
    <% if logged_in? && current_user.played?(@song) %>
      <%= render "panel", title: "Edit" do %>
        <div class="panel-body">
          <%= form_for @song, remote: true do |f| %>
            <div class="form-group">
              <%= f.label :status %>
              <%= f.select :status, {"Private": "secret", "Closed": "closed", "Public": "open"}, {}, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :comment, class: "form-control", rows: 3 %>
            </div>
            <%= f.submit "Save", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
    <% elsif !@song.comment.blank? %>
      <%= render "panel", title: "Comments" do %>
        <div class="panel-body">
          <%= simple_format(@song.comment) %>
        </div>
      <% end %>
    <% end %>
  </div>
  <nav>
    <ul class="pager">
      <% p = @song.previous(logged_in?) %>
      <li class="previous <%= p.nil? ? 'disabled' : '' %>">
        <%= link_to p do %>
          <span aria-hidden="true">&larr; </span>Previous
        <% end %>
      </li>
      <% n = @song.next(logged_in?) %>
      <li class="next <%= n.nil? ? 'disabled' : '' %>">
        <%= link_to n do %>
          Next<span aria-hidden="true"> &rarr;</span>
        <% end %>
      </li>
    </ul>
  </nav>
</article>

app/views/songs/update.js.erb
$("<%= j render('layouts/flash') %>").prependTo('#main').hide().fadeIn().delay(5000).fadeOut();