config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "stats", to: "static_pages#stats"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, path: :members do
    resource :admin, only: %i(create destroy)
  end
  resources :songs
  resources :lives
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)

  namespace :api, format: "json" do
    namespace :v1 do
      resources :users, only: %i[index show], path: :members
      resources :lives, only: %i[index show]
      resources :songs, only: %i[index show]
      post "/login", to: "tokens#create"
      delete "/logout", to: "tokens#destroy"
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-center">
  &copy; 2019 by wataridori. All Rights Reserved.
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "LiveLog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= current_page?(songs_path) ? "active" : "" %>">
        <%= link_to "Song Search", songs_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= params[:controller] == "lives" ? "active" : "" %>">
        <%= link_to "Live List", lives_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= params[:controller] == "users" ? "active" : "" %>">
        <%= link_to "Members", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= current_page?(stats_path) ? "active" : "" %>">
        <%= link_to "Stats", stats_path, class: "nav-link" %>
      </li>
    </ul>
    <% if logged_in? %>
      <ul class="navbar-nav ml-auto">
        <% if current_user.admin_or_elder? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "New Live", new_life_path, class: "dropdown-item" %>
              <%= link_to "New Member", new_user_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.full_name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to glyphicon(:user) + "Profile", current_user, class: "dropdown-item" %>
            <%= link_to glyphicon(:comment) + "Report", feedback_url(current_user), target: "_blank", class: "dropdown-item" %>
            <%= link_to glyphicon(:cog) + "Settings", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to glyphicon("sign-out-alt") + "Logout", logout_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      </ul>
    <% else %>
      <%= link_to login_path do %>
        <button class="btn btn-default.navbar-btn.navbar-right"><%= glyphicon("sign-in-alt") + "Login" %></button>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "shared/page-level-ads" if Rails.env.production? && !logged_in? %>
    <%= render "layouts/shim" %>
    <%= favicon_link_tag "favicon.ico" %>
  </head>

  <body>
    <%= render "shared/analyticstracking" if Rails.env.production? %>
    <%= render "layouts/header" %>
    <div id="main" class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
      <aside><%= render "shared/content-ads" if Rails.env.production? && !logged_in? %></aside>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>